accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import signup


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("home")),
    ),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptView,
    ReceiptCreate,
    ExpenseCategoryView,
    AccountView,
    ExpenseCreate,
    AccountCreate,
)

urlpatterns = [
    path("", ReceiptView.as_view(), name="home"),
    path("create/", ReceiptCreate.as_view(), name="create_receipt"),
    path("categories/", ExpenseCategoryView.as_view(), name="category_view"),
    path("accounts/", AccountView.as_view(), name="account_view"),
    path(
        "categories/create/", ExpenseCreate.as_view(), name="create_category"
    ),
    path("accounts/create/", AccountCreate.as_view(), name="create_account"),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL,
        related_name="receipts",
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.shortcuts import render, redirect

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import render, redirect
from receipts.models import ExpenseCategory, Account, Receipt
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class ReceiptView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/receipt_view.html"


class ReceiptCreate(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/receipt_create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expenses/expense_view.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/account_view.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCreate(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expenses/expense_create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("category_view")


class AccountCreate(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/account_create.html"
    fields = [
        "name",
        "number",
    ]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("account_view")

receipts/templates/accounts/account_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
</head>

<body>
    <header>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_authenticated is False %}
            <li>
                <a href="{% url 'signup' %}">Signup</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </header>
    <main>
        <div>
            <h1>Create Account</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/accounts/account_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account View</title>
</head>

<body>
    <header>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_authenticated is False %}
            <li>
                <a href="{% url 'signup' %}">Signup</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </header>
    <main>
        <h1>My Accounts</h1>
        <table>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of receipts</th>
            </tr>
            {% for item in user.accounts.all %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.number }}</td>
                <td>{{ item.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </table>
    </main>
</body>

</html>

receipts/templates/expenses/expense_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Expense</title>
</head>

<body>
    <header>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_authenticated is False %}
            <li>
                <a href="{% url 'signup' %}">Signup</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </header>
    <main>
        <div>
            <h1>Create Expense</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/expenses/expense_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Expense Category View</title>
</head>

<body>
    <header>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_authenticated is False %}
            <li>
                <a href="{% url 'signup' %}">Signup</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </header>
    <main>
        <h1>My Expenses</h1>
        <p><a href="{% url 'create_category' %}">Create Expense</a></p>
        <table>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
            {% for item in user.categories.all %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </table>
    </main>
</body>

</html>

receipts/templates/receipts/receipt_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Receipt</title>
</head>

<body>
    <header>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_authenticated is False %}
            <li>
                <a href="{% url 'signup' %}">Signup</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </header>
    <main>
        <div>
            <h1>Create Receipt</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
</body>

</html>

receipts/templates/receipts/receipt_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Receipt View</title>
</head>

<body>
    <header>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
            {% if user.is_authenticated is False %}
            <li>
                <a href="{% url 'signup' %}">Signup</a>
            </li>
            <li>
                <a href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
        </ul>
    </header>
    <main>

        <h1>My Receipts</h1>
        <table>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th><a href="{% url 'create_category' %}">Category</a></th>
                <th>Account</th>
            </tr>
            {% for item in receipt_list %}
            <tr>
                <td>{{ item.vendor }}</td>
                <td>{{ item.total }}</td>
                <td>{{ item.tax }}</td>
                <td>{{ item.date }}</td>
                <td>{{ item.category }}</td>
                <td>{{ item.account }}</td>
            </tr>
            {% endfor %}
        </table>
    </main>
</body>

</html>